# Generated by Django 5.0.4 on 2024-04-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseideologyprojects',
            name='leaderID',
        ),
        migrations.RemoveField(
            model_name='courseideologyprojects',
            name='resultSubmission',
        ),
        migrations.AddField(
            model_name='courseideologyprojects',
            name='leader',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='courseideologyprojects',
            name='results',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseideologyprojects',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing'), ('completed', 'Completed')], max_length=10),
        ),
    ]
