# Generated by Django 5.0.4 on 2024-04-11 04:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_courseideologyprojects_leaderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseideologyprojects',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
