# Generated by Django 5.0.4 on 2024-04-11 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_courseideologyprojects_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseideologyprojects',
            name='leaderID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='led_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courseideologyprojects',
            name='leader',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
