# Generated by Django 5.0.4 on 2024-04-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
