# Generated by Django 5.0.4 on 2024-05-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_courseideologyprojects_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidTermReview',
            fields=[
                ('project_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='项目名称')),
                ('achievements', models.TextField(verbose_name='已取得的成果')),
                ('next_steps', models.TextField(verbose_name='下一步的计划')),
                ('issues', models.TextField(verbose_name='存在的问题')),
                ('solutions', models.TextField(verbose_name='拟解决措施')),
                ('review_comments', models.TextField(verbose_name='中期检查审核意见')),
            ],
            options={
                'verbose_name': '中期检查信息',
                'verbose_name_plural': '中期检查信息',
            },
        ),
        migrations.CreateModel(
            name='ProjectFinalReport',
            fields=[
                ('project_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='项目名称')),
                ('results_summary', models.TextField(verbose_name='项目成果汇总')),
                ('main_research_content', models.TextField(verbose_name='项目主要研究内容')),
                ('ideological_education_significance', models.TextField(verbose_name='项目的思政教育意义')),
                ('final_report_comments', models.TextField(verbose_name='结项报告审核意见')),
            ],
            options={
                'verbose_name': '项目结项报告',
                'verbose_name_plural': '项目结项报告',
            },
        ),
        migrations.RemoveField(
            model_name='courseideologyprojects',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='courseideologyprojects',
            name='projectID',
        ),
        migrations.RemoveField(
            model_name='courseideologyprojects',
            name='resourceLink',
        ),
        migrations.AlterField(
            model_name='courseideologyprojects',
            name='projectName',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
