# Generated by Django 5.0.4 on 2024-05-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_midtermreview_projectfinalreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseideologyprojects',
            name='final_report_submitted',
            field=models.BooleanField(default=False, verbose_name='结项报告已提交'),
        ),
        migrations.AddField(
            model_name='courseideologyprojects',
            name='midterm_report_submitted',
            field=models.BooleanField(default=False, verbose_name='中期报告已提交'),
        ),
    ]
