# Generated by Django 5.0.4 on 2024-05-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_courseideologyprojects_final_report_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermreview',
            name='midterm_review_Status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='projectfinalreport',
            name='final_report_Status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
