# Generated by Django 5.0.4 on 2024-05-02 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_midtermreview_midterm_review_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseideologyprojects',
            name='projectStatus',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '审批通过'), ('rejected', '审批不通过')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='courseideologyprojects',
            name='status',
            field=models.CharField(choices=[('planning', '规划中'), ('ongoing', '进行中'), ('completed', '已完成')], max_length=10),
        ),
    ]
