# Generated by Django 5.0.4 on 2024-05-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_courseideologyprojects_projectstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midtermreview',
            name='midterm_review_Status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '审批通过'), ('rejected', '审批不通过')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectfinalreport',
            name='final_report_Status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '审批通过'), ('rejected', '审批不通过')], default='pending', max_length=10),
        ),
    ]
