# Generated by Django 5.0.4 on 2024-05-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_midtermreview_midterm_review_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoneyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名称')),
                ('projectPerson', models.CharField(max_length=100, verbose_name='申请人')),
                ('requested_funding', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='申请的经费')),
                ('funding_purpose', models.TextField(verbose_name='经费主要用途')),
                ('contact_info', models.CharField(max_length=100, verbose_name='申请人的联系方式')),
                ('application_date', models.DateField(verbose_name='申请日期')),
            ],
            options={
                'verbose_name': '项目报表',
                'verbose_name_plural': '项目报表',
            },
        ),
    ]
