# Generated by Django 5.0.4 on 2024-05-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_moneyreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseideologyprojects',
            name='application_submitted',
            field=models.BooleanField(default=False, verbose_name='申请已提交'),
        ),
        migrations.AddField(
            model_name='moneyreport',
            name='money_report_Status',
            field=models.CharField(choices=[('pending', '待审批'), ('approved', '审批通过'), ('rejected', '审批不通过')], default='pending', max_length=10),
        ),
    ]
