# Generated by Django 5.0.4 on 2024-05-07 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_courseideologyprojects_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='midtermreview',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_reviews', to='app.courseideologyprojects'),
        ),
        migrations.AddField(
            model_name='projectfinalreport',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_reports', to='app.courseideologyprojects'),
        ),
    ]
